appname = core_amazon_crud
httpport = ${CORE_AMAZON_CRUD_CORE_API_HTTP_PORT}
runmode = prod
EnableDocs = true

parameterStore =${PARAMETER_STORE}
PGuser         =${CORE_AMAZON_CRUD_CORE_API_DB_USER}
PGpass         =${CORE_AMAZON_CRUD_CORE_API_DB_PASS}
PGhost         =${CORE_AMAZON_CRUD_CORE_API_DB_URL}
PGport         =${CORE_AMAZON_CRUD_CORE_API_DB_PORT}
PGdb           =${CORE_AMAZON_CRUD_CORE_API_DB_NAME}
PGschema       =${CORE_AMAZON_CRUD_CORE_API_DB_SCHEMA}
